enum ModelDeviceProblemType { 
  INSUFFICIENT_VRAM, 
  INSUFFICIENT_STORAGE, 
  BAD_LOAD_SUCCESS_HISTORY, 
  BAD_PERFORMANCE_HISTORY,
  DEVELOPER_MODE,
  BETA
}

export default ModelDeviceProblemType;