name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: DecentAppsNet/deploy@v1
    with:
      app-name: ${{ vars.APP_NAME }}
    secrets:
      api-key: ${{ secrets.DECENT_API_KEY }}