name: Rollback Production to Previous Version

on:
  workflow_dispatch:

jobs:
  rollback:
    uses: DecentAppsNet/rollback@v1
    with:
      app-name: ${{ vars.APP_NAME }}
    secrets:
      api-key: ${{ secrets.DECENT_API_KEY }}